reporter:
    ip: 127.0.0.1
    port: 3000
    enabled: false

reflectors:
  p25:
    enabled: true
    networkPort: 32010
    networkDebug: false

  nxdn:
    enabled: true
    networkPort: 32020
    networkDebug: false
    targetGroup: 1

  ysf:
    enabled: true
    networkPort: 32030
    networkDebug: false
