logger:
    path: "./logs/"

reporter:
    ip: 127.0.0.1
    port: 3000
    enabled: false

reflectors:
  p25:
    enabled: true
    networkPort: 32010
    networkDebug: false

  nxdn:
    enabled: true
    networkPort: 32020
    networkDebug: false
    targetGroup: 1

  ysf:
    enabled: true
    networkPort: 32030
    networkDebug: false

  m17:
    enabled: true
    networkPort: 12345
    reflector: "001" # This is the three characters after "M17-"; for example if you are M17-ABC the value for this config would be ABC
    modules:
      - module: A
        enabled: true
      - module: B
        enabled: true
    networkDebug: false
